###
DELETE http://localhost:8443/api/user/{{id}}

###
DELETE http://localhost:8443/api/role/{{id}}

#测试获取全部角色
GET http://localhost:8443/api/role/all
Accept: application/json

###
#测试获取全部用户
GET http://localhost:8443/api/user/all
Accept: application/json

###
#测试增加用户
POST http://localhost:8443/api/user
Content-Type: application/json

{
  "id": 0,
  "name": "testing",
  "password": "123",
  "role": {
    "id": 1,
    "name": "admin",
    "desc": "经理"
  }
}

###
POST http://localhost:8443/api/role
Content-Type: application/json

{
  "id": 0,
  "name": "test222",
  "desc": "test11"
}
